default: &default
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV['DB_HOST'] || Rails.application.credentials.development[:database_host] %>"
  post: "<%= ENV['DB_PORT'] || Rails.application.credentials.development[:database_port] %>"
  username: "<%= ENV['DB_USERNAME'] || Rails.application.credentials.development[:database_username] %>"
  password: "<%= ENV['DB_PASSWORD'] || Rails.application.credentials.development[:database_password] %>"
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: very_clean_development
test:
  <<: *default
  database: very_clean_test
production:
  <<: *default
  database: very_clean_production
  username: very_clean
  password: <%= ENV['VERY_CLEAN_DATABASE_PASSWORD'] %>
