export const CREATE_PROJECT = 'CREATE_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const REQUEST = '_REQUEST'
export const SUCCESS = '_SUCCESS'
export const ERROR = '_ERROR'

export const CREATE_TASK = 'CREATE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const LOAD_TASKS = 'LOAD_TASKS'
export const MOVE_TASK_HIGHER = 'MOVE_TASK_HIGHER'
export const MOVE_TASK_LOWER = 'MOVE_TASK_LOWER'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'

export const SHOW_PROJECT_FORM_BUTTONS = 'SHOW_PROJECT_FORM_BUTTONS'
export const HIDE_PROJECT_FORM_BUTTONS = 'HIDE_PROJECT_FORM_BUTTONS'

export const SIGN_IN_USER = 'SIGN_IN_USER'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'
export const SIGN_UP_USER = 'SIGN_UP_USER'

export const CLEAR_AUTH_FORM = 'CLEAR_AUTH_FORM'
